### ISSUE TITLE
Beta SDK depends on "Nito.AsyncEx" version="5.0.0-pre-02"

### ISSUE THREAD

**Issue by ndastur** [ably/ably-dotnet#121]
I have been trying out the new beta of the SDK as per our other discussions but the new beta depends on ```<dependency id="Nito.AsyncEx" version="5.0.0-pre-02" />```

Is there a good reason for the dependence on a pre-release third party package. The new Nito.Async v5 certainly breaks my app and will delay the release of this package into production

**Comment by marto83** [comment]
@ndastur sorry to hear it breaks your app. I only use a small portion of this library and made sure there were not any changes to the parts I'm using. I also updated it because it solved a dependency issue I was having with using the library on another platform. 

However, this week I will pull the source files for the classes I'm using into ably and remove it as a dependency. Sorry, it delaying your build. Please use 0.8.5-beta12 for the time being. I'll update you tomorrow with any progress.

**Comment by marto83** [comment]
@ndastur as promised in the latest beta **0.8.5-beta16** the nito async library is no longer a dependency and I've inlined the 4.0.1 implementation. I'm going to close this issue.

**Comment by ndastur** [comment]
Thank you. I'll give it a whirl
