### ISSUE TITLE
Integrate a Linter/Code formatting tool into the build process

### ISSUE THREAD

**Issue by withakay** [ably/ably-dotnet#179]
Integrate a Linter/Code formatting tool into the build process to increase code quality and consistency.

I suggest waiting for https://github.com/dotnet/codeformatter to mature past alpha and then evaluating that.

**Comment by withakay** [comment]
@funkyboy @paddybyers 

I have been testing https://github.com/DotNetAnalyzers/StyleCopAnalyzers and it works well and has rules that cover the various white space issues mentioned rule for curly braces with `if` statements (and many, many others that could prove useful). Rule violations display as hints in the Visual Studio editor and as build warnings by default, although all the rules can have a severity level set, setting the level to Error causes the build to fail.

My preference would be to aim to standardise on the the code style used by the .Net team outlined here https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md. This is the closest thing to a standard for c# style.

The good new is that the actual Ably library code is very clean, it is the test code that is the problem, there are hundreds of warnings (but most of them trivial stuff).

Assuming you agree that adopting StyleCopAnalyzers is a good idea (and that is my recommendation), it would be good to discuss how best to do so. For example, we could just add the rules and just clean up as we go or we could make a concerted effort to clean up the code base before adding anymore features, or something in between perhaps. A lot of the fixes can be semi-automated with Resharper, so the task is not as huge as it might first appear.

**Comment by paddybyers** [comment]
I agree we should adopt it or something like it.

If a large fraction of the warnings come from a small number of nonstandard style choices, we could consider updating the settings to quieten those, assuming we're happy with them.

If we do want to go ahead and fix them, then it depends on the effort required to clean it up. I have a strong preference for just biting the bullet and doing it because otherwise you just introduce new complexities. (For example, in realtime, we have 2 standards; the legacy standard and the new standard and the aim is to migrate code that we touch but not do a wholesale update. But that's just a pain and it itself has a cost to setup and maintain.)

Is there an easy way to estimate the level of effort required?

**Comment by withakay** [comment]
> Is there an easy way to estimate the level of effort required?

It took me about an hour to get a 90% reduction in warnings (via fixes mostly and some disabling of rule), there are still 150 or so. The difficulty is not linear, but I think another hour or so and I would get another 90%

I have started a WIP PR https://github.com/ably/ably-dotnet/pull/190

**Comment by paddybyers** [comment]
If it's a matter of hours then I definitely think we should bite the bullet and bring it all up to the new standard.
