### ISSUE TITLE
IO.Ably.AblyAuth RequestTokenAsync timeout exception not catchable

### ISSUE THREAD

**Issue by bchenhs** [ably/ably-dotnet#366]
We are seeing exceptions being thrown from IO.Ably.AblyAuth RequestTokenAsync request timeout. In the consuming client, since there is no handle for us to try/catch around, this becomes an unhandled exception at the AppDomain level.

This exception should be either:
1. surfaced through an error callback somewhere, if you require consuming client to respond to it, or 
2. handled silently within AblyRealtime.

It will be a good idea to audit the code to identify other areas where exceptions are not handled within the AblyRealtime client.

**Comment by withakay** [comment]
Hi,

Thanks for reporting this issue.
RequestTokenAsync is designed to bubble exceptions up to the caller, which should then handle them and respond accordingly (retry, change the connection state etc.) and as you suggest pass the error as a call back to a supplied handler if the connection state changes due to the exception.

Do you have a stack trace you could pass on?
That would be useful in getting started with a fix for this issue.

Thanks

**Comment by bchenhs** [comment]
Error message: 
[ErrorInfo Reason: Error executing request. Request timed out. (See https://help.ably.io/error/50000); Code: 50000; Href: https://help.ably.io/error/50000]

Stack:
IO.Ably.AblyHttpClient in InternalSendAsync at line 117:0
Called from: System.Runtime.CompilerServices.TaskAwaiter in ThrowForNonSuccess
IO.Ably.AblyHttpClient in Execute at line 751:0

IO.Ably.AblyHttpClient in Execute at line 1951:0
Void MoveNext()
Called from: System.Runtime.CompilerServices.TaskAwaiter in ThrowForNonSuccess
IO.Ably.AblyRest in ExecuteRequest at line 388:0
Called from: System.Runtime.ExceptionServices.ExceptionDispatchInfo in Throw
IO.Ably.AblyRest in ExecuteRequest at line 1200:0
Called from: System.Runtime.CompilerServices.TaskAwaiter in ThrowForNonSuccess
IO.Ably.AblyRest+<ExecuteRequest>d__36`1 in MoveNext at line 114:0
Called from: System.Runtime.CompilerServices.TaskAwaiter in ThrowForNonSuccess
IO.Ably.AblyAuth in RequestTokenAsync at line 1952:0
Called from: System.Runtime.CompilerServices.TaskAwaiter in ThrowForNonSuccess
IO.Ably.AblyAuth in AuthorizeAsync at line 248:0
Called from: System.Runtime.CompilerServices.TaskAwaiter in ThrowForNonSuccess
IO.Ably.Transport.ConnectionManager in RetryAuthentication at line 448:0
Called from: System.Runtime.CompilerServices.TaskAwaiter in ThrowForNonSuccess
IO.Ably.Transport.States.Connection.ConnectionConnectedState+<<OnMessageReceived>b__8_0>d in MoveNext at line 111:0
Called from: System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c in ThrowAsync { <lambda> }

**Comment by codemerx** [comment]
@withakay Judging by the stack trace it seems that happens when `AUTH` message gets received and not on a direct call of `RequestTokenAsync`. In `OnMessageReceived` we run the processing of the `AUTH` message through `RunInBackground` and that seems to be susceptible to a race condition. If it gets a long running task that throws exception in the end as an argument (e.g. `RequestTokenAsync` with multiple retries) the `Exception` property of that task might never get read  in the handler provided by `ContinueWith` since the GC might try collecting that task before it finishes and `ContinueWith` kicks in. If the GC tries collecting a `Task` which `Exception` property is non null and never been read then this exception will get rethrown. 

Haven't really tested this, yet, but might be worth pursuing. @bchenhs how often do you, guys, get this?

**Comment by bchenhs** [comment]
@codemerx We are seeing this 50-100 times a day from roughly 30,000 active users.

**Comment by codemerx** [comment]
@bchenhs Does 1.1.13 fix this exception for you?

On a side note, are you getting any other unhandled exceptions? If so, please, do not hesitate to report them. Stuff like this we would really like to fix.

**Comment by tomczoink** [comment]
<div>Agent Tom Camp linked Freshdesk ticket <a href="https://ably.freshdesk.com/a/tickets/102134">102134 </a>for this issue</div>

**Comment by codemerx** [comment]
Thanks @bchenhs. Please, keep us posted.

**Comment by bchenhs** [comment]
Hi, looks like this issue is resolved. Thanks for getting the fix out and making the dotnet client even better!

**Comment by paddybyers** [comment]
Good to hear, thanks for the update
