### ISSUE TITLE
MessageExtras to comply with TM2i

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-dotnet#422]
Originally specified: https://github.com/ably/ably-java/issues/580

And fixed in: https://github.com/ably/ably-java/pull/581

**Comment by QuintinWillison** [comment]
@sacOO7 it may be that this issue can simply be closed - can you validate if this has been fixed, or create a PR to fix accordingly. Thanks.

**Comment by sacOO7** [comment]
Findings with respect to https://github.com/ably/ably-java/pull/581
- ```MessageExtras``` does not check for null ```data (JToken)``` in the constructor.
- ```DeltaExtras``` does not check for null ```Format``` and ```From``` values.
- ```ToJson()``` method can be simplified, ```data (Jtoken)``` already contains Delta property.

**Comment by sacOO7** [comment]
Note - As per https://docs.ably.io/client-lib-development-guide/features/#TM2i, JsonObject is specified as optional (nullable) value.
Need to confirm if its null or non-null.

**Comment by marto83** [comment]
I leave it `null` because this way we don't serialise an empty json object (`{}`) when sending the message to the server. Same for `From` and `Format`. If the client are never going to set them we can probably make the constructor private. 

Agree about `ToJson()` now everything is immutable we can simplify it.

**Comment by sacOO7** [comment]
@QuintinWillison we will need your inputs on this https://github.com/ably/ably-dotnet/issues/422#issuecomment-667641809
