### ISSUE TITLE
Custom AuthUrl gets called twice.

### ISSUE THREAD

**Issue by lovetofail** [ably/ably-dotnet#58]
When I set my custom AuthUrl in a network sniffer I can see that it gets called twice each time.
```
var ablyRealtime = new AblyRealtime(new ClientOptions()
            {
                Key = "",
                AuthUrl = "HTTP://MYWEBSITE.COM/PATH,
            });
```
I think it's something todo with this part
```
            if (mergedOptions.AuthUrl.IsNotEmpty())
            {
                var response = await CallAuthUrl(mergedOptions, @params);
```

**Comment by mattheworiordan** [comment]
Hi @lovetofail, which branch are you working off, or are you off master?  Can you confirm which version as we've been making a significant number of updates recently

**Comment by lovetofail** [comment]
It's specs/realtime-connection-part2, but I'm seeing it for a few weeks at least.
https://github.com/ably/ably-dotnet/commit/c93ac172ca49c0431605c5e68cc58fe5567725f0

**Comment by mattheworiordan** [comment]
@marto83 can you take a look please?

**Comment by marto83** [comment]
I'll have a look in the morning. Thanks for pointing it out

**Comment by marto83** [comment]
@lovetofail I had a look and can't replicate the issue. I suspect you are using on older version of the client and I'm only saying that because a week or so ago I changed the AuthUrl to be of type Uri so you'd need to do new Uri(....). 

I also created a test for and this is the debug output from the test:
https://github.com/ably/ably-dotnet/commit/e0658bc417820077b5d75e8b121e61cac7ba7715

Ably: [Debug] 10:19:25.134 #14 Protocol set to: Json
Ably: [Debug] 10:19:25.134 #14 Initializing message encodings. json,utf-8,cipher,base64 initialized
Ably: [Info] 10:19:25.134 #14 Using token authentication.
Ably: [Info] 10:19:25.134 #14 Authentication method: Token auth with URL
Ably: [Debug] 10:19:25.150 #15 ConnectionManager thread created
Ably: [Debug] 10:19:25.166 #15 xx Connecting: BeforeTransition
Ably: [Debug] 10:19:25.166 #15 Connection notifying subscribers for state change `Connecting`
Ably: [Debug] 10:19:25.166 #14 [98bf07fb] Waiting for state Connected for 5 seconds
Ably: [Debug] 10:19:25.166 #15 xx Connecting: Attaching state 
Ably: [Debug] 10:19:25.166 #15 Creating transport
**Ably: [Info] 10:19:25.166 #15 Sending GET request to http://echo.ably.io/?type=text&body=JA0NyQ.D5aYoImdUzb4vdjdRFUjxAu8-zD--9jl-CW86n5t9MH_MCQ8HKn14n5TApZKHdvENIGkMe8oCvXXxjb2qagOMzWBQTIz-QX_Y9KkT6RMKVZacLiED4gin98kAZ6jEsp4H
Ably: [Debug] 10:19:25.166 #15 Executing request: http://echo.ably.io/?type=text&body=JA0NyQ.D5aYoImdUzb4vdjdRFUjxAu8-zD--9jl-CW86n5t9MH_MCQ8HKn14n5TApZKHdvENIGkMe8oCvXXxjb2qagOMzWBQTIz-QX_Y9KkT6RMKVZacLiED4gin98kAZ6jEsp4H**
Ably: [Debug] 10:19:25.235 #15 Connecting to web socket on url: wss://sandbox-realtime.ably.io/?accessToken=JA0NyQ.D5aYoImdUzb4vdjdRFUjxAu8-zD--9jl-CW86n5t9MH_MCQ8HKn14n5TApZKHdvENIGkMe8oCvXXxjb2qagOMzWBQTIz-QX_Y9KkT6RMKVZacLiED4gin98kAZ6jEsp4H&v=0.8&format=json&echo=true
Ably: [Debug] 10:19:25.235 #15 Connecting socket
Ably: [Debug] 10:19:25.235 #15 Setting up timer 'Connecting state timer' to run action after 10 seconds. Autoreset: False
Ably: [Debug] 10:19:25.235 #15 xx Connecting: Completed setting state
Ably: [Debug] 10:19:25.421 #12 Websocket opened!
Ably: [Debug] 10:19:25.424 #15 On transport event. State Connected error 
Ably: [Debug] 10:19:25.427 #12 Websocket message received. Raw: {"action":4,"connectionId":"6AYkzh3bzx","connectionKey":"1082b!6AYkzh3bzxVhxxbe-119c1082b","connectionSerial":-1,"connectionDetails":{"clientId":"*","connectionKey":"1082b!6AYkzh3bzxVhxxbe-119c1082b","maxMessageSize":16384,"maxInboundRate":250,"maxFrameSize":262144,"serverId":"frontend.1be5.eu-central-1-A.i-305dca8c","connectionStateTtl":120000}}
Ably: [Debug] 10:19:25.429 #15 Message received: {"action":4,"connectionId":"6AYkzh3bzx","connectionKey":"1082b!6AYkzh3bzxVhxxbe-119c1082b","connectionSerial":-1,"connectionDetails":{"clientId":"*","connectionKey":"1082b!6AYkzh3bzxVhxxbe-119c1082b","maxMessageSize":16384,"maxInboundRate":250,"maxFrameSize":262144,"serverId":"frontend.1be5.eu-central-1-A.i-305dca8c","connectionStateTtl":120000}}
Ably: [Debug] 10:19:25.437 #15 ConnectionManager: Message Received { action=Connected }
Ably: [Debug] 10:19:25.440 #15 Aborting timer 'Connecting state timer'
Ably: [Debug] 10:19:25.440 #15 Aborting timer 'Connecting state timer'
Ably: [Debug] 10:19:25.440 #15 xx Connected: BeforeTransition
Ably: [Debug] 10:19:25.441 #15 Connection notifying subscribers for state change `Connected`
Ably: [Debug] 10:19:25.442 #15 [98bf07fb] Desired state was reached.
Ably: [Debug] 10:19:25.442 #15 [98bf07fb] Removing Connection listener
Ably: [Debug] 10:19:25.442 #15 xx Connected: Attaching state 
Ably: [Debug] 10:19:25.445 #15 xx Connected: Completed setting state

Let me know if I'm missing something and I'll retest it tomorrow.

**Comment by lovetofail** [comment]
This is a project with Ably.ConsoleTest, if you need it https://www.dropbox.com/s/pxgpo6l6wnv0x0w/ably-dotnet.zip?dl=1
On a screenshot you can see that program calls requestToken twice
![capture](https://cloud.githubusercontent.com/assets/4531542/15281721/64d3b3c0-1b46-11e6-92cc-ec65f63a6c2c.PNG)

**Comment by marto83** [comment]
I see it now. Looking into it.

**Comment by marto83** [comment]
@lovetofail I found the issue. It is a race condition when the realtime client is initialised by default it automatically connects but when you call Connect straight after the client hasn't transition fully to Connecting so it retries again. I'll get that fixed. 

Thank you again :)

**Comment by marto83** [comment]
@lovetofail. I've added an extra check to make sure that doesn't happen any more. Do you want to try again and let me know. 
I'm finishing the connection specs today and will move to channels and presence.

**Comment by lovetofail** [comment]
Seems to be fixed, but present when I call ablyRealtime.RestClient.Auth.RequestToken();
This is not urgent in any way. This library is already sufficient for my needs.

```
var options = new ClientOptions()
            {
                AuthUrl = new Uri("https://www.ably.io/ably-auth/token-request/demos"),                
                ClientId = "stan",
                Tls = false,                
            };
            var ablyRealtime = new AblyRealtime(options);
            var param = new TokenParams { };
            var tokenDetails = await ablyRealtime.RestClient.Auth.RequestToken();
```
![capture](https://cloud.githubusercontent.com/assets/4531542/15288076/65a8a2e0-1b70-11e6-90a4-b0ff208c25e5.PNG)

**Comment by marto83** [comment]
@lovetofail that is expected. You are manually requesting a new token. It will not wait or reuse the current one the library has. 
I'm going to close this issue but keep me posted if you find anything else.
