### ISSUE TITLE
Unable to recover connection: not found

### ISSUE THREAD

**Issue by lovetofail** [ably/ably-dotnet#69]
Ttl is 70 sec. After few reauths connection hangs. It says that it's Connected but in web dev console user leaves. Also you can see that in the end there is no reauths happening anymore.
http://pastebin.com/t29VgaDM

**Comment by marto83** [comment]
@lovetofail seems to be an issue with the lib when it can't recover the previous connection. I'm looking into it today. The connected state doesn't fully attach and is not processing messages. 
I've managed to replicate it and will get it fixed.

**Comment by mattheworiordan** [comment]
Hi @lovetofail 

So I can see the problem:

```
Websocket data message received. Raw: { "action" : 4, "error" : { "message" : "Unable to recover connection: not found (OqVNcub87UzT_os5)", "code" : 80008, "statusCode" : 400 }, "connectionId" : "1agNzvcJuk", "connectionKey" : "e7daa271!1agNzvcJukdGsy9n-18020e7daa271", "connectionSerial" : -1, "connectionDetails" : { "clientId" : "stan", "connectionKey" : "e7daa271!1agNzvcJukdGsy9n-18020e7daa271", "maxMessageSize" : 16384, "maxInboundRate" : 15, "maxFrameSize" : 262144, "serverId" : "frontend.4236.us-east-1-A.i-68e00cee", "connectionStateTtl" : 120000 } }
```

What this means is that the connection has not been able to resume for some reason.  Typically this happens because you have been disconnected for more than two minutes, but it is possible that connection state is lost for other edge case reasons.  In this case, I am going to look into why your connection state was lost, but regardless you should be reattaching channels `on('connected')` as when the connection state is lost, the channels become detached.

So that you know, we are very soon to release a minor update to our spec that auto-reattaches channels and enters presence when a connection cannot resume i.e. exactly this use case.  In the mean time, I suggest you listen for `on('connected')` and reattach any channels that are detached until this change is rolled out.

See https://www.ably.io/documentation/realtime/connection#connection-state-explained for more info.

Shout if you want to discuss any of this or I have been unclear.

Matt

**Comment by lovetofail** [comment]
http://pastebin.com/eVcqUJen 
Connection state fails after few reauths.
I guess somewhat similar - "Unable to recover connection (connection expired)", "code" : 80008, "statusCode" : 404
```
static void Main(string[] args)
        {
            Logger.LogLevel = LogLevel.Debug;
            try
            {
                var client = Realtime.Test();
                client.Connection.ConnectionStateChanged += Connection_ConnectionStateChanged;
                client.Connect();
                channel = client.Get("ubfp:presence");
                channel.Presence.EnterClient("stan", "mydata");
                Console.ReadLine();
                ConsoleColor.Green.WriteLine("Success!");
            }
            catch (Exception ex)
            {
                ex.LogError();
            }
        }

        private static void Connection_ConnectionStateChanged(object sender, Ably.Realtime.ConnectionStateChangedEventArgs e)
        {
            if (e.CurrentState == ConnectionStateType.Connected)
            {
                Logger.LoggerSink.LogEvent(LogLevel.Debug, "=======Connect Count: " + ConnectCount++);
                if (channel.State == ChannelState.Attached)
                    channel.Detach();
                channel.Attach();
            }
        }
```

**Comment by mattheworiordan** [comment]
@lovetofail want to chat on Slack, might be easier to get to the bottom of all this and get this resolved?  I can send you an invite, just send an email to support@ably.io and I will add your email to our Slack channel.

Also, thanks for all your help finding issue with the .NET lib.  As you know, it's had a lot of work done to it recently so having your help is HUGELY appreciated.
